name: Build Extension
on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: 🐧 Linux (GCC)
            os: ubuntu-22.04
            platform: linux

        #   - name: 🐧 Linux (GCC, Double Precision)
        #     os: ubuntu-22.04
        #     platform: linux
        #     flags: precision=double

        #   - name: 🏁 Windows (x86_64, MSVC)
        #     os: windows-2019
        #     platform: windows

        #   - name: 🏁 Windows (x86_64, MinGW)
        #     os: windows-2019
        #     platform: windows
        #     flags: use_mingw=yes

        #   - name: 🍎 macOS (universal)
        #     os: macos-latest
        #     platform: macos
        #     flags: arch=universal

        #   - name: 🤖 Android (arm64)
        #     os: ubuntu-22.04
        #     platform: android
        #     flags: arch=arm64

        #   - name: 🍏 iOS (arm64)
        #     os: macos-latest
        #     platform: ios
        #     flags: arch=arm64

        #   - name: 🌐 Web (wasm32)
        #     os: ubuntu-22.04
        #     platform: web

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Restore OpenCV
        uses: actions/cache/restore@v4
        with:
          path: opt/opencv/
          key: opencv4.10-${{ matrix.platform }}
          fail-on-cache-miss: true

      - name: Install scons
        run: python -m pip install scons==4.0.0

      - name: Update submodule
        run: git submodule update --init
  
      - name: Build godot-cpp (debug)
        run: |
            scons platform=${{ matrix.platform }} disable_exceptions=false verbose=yes target=template_debug ${{ matrix.flags }}

      - name: Build godot-cpp (release)
        run: |
            scons platform=${{ matrix.platform }} disable_exceptions=false verbose=yes target=template_release ${{ matrix.flags }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GDOpenCV-${{ matrix.platform }}
          path: |
            ${{ github.workspace }}/demo/bin/**
  merge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: GDOpenCV-all
          pattern: GDOpenCV-*
          delete-merged: true
